openapi: 3.0.0
info:
  title: Sensor Data API
  version: 1.0.0
  description: API para gerenciar leituras de sensores, usuários e estatísticas.
servers:
  - url: http://localhost:5000
    description: Servidor local
  - url: https://airlytcs-backend.onrender.com
    description: Servidor de produção
paths:
  /readings:
    post:
      summary: Criar uma nova leitura
      description: Cria uma nova entrada de leitura no banco de dados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                humidity:
                  type: number
                  example: 50
                temperature:
                  type: number
                  example: 22.5
                mq_sensor_value:
                  type: number
                  example: 450
                mq_voltage:
                  type: number
                  example: 2.5
                timestamp:
                  type: string
                  format: date-time
              required:
                - humidity
                - temperature
                - mq_sensor_value
                - mq_voltage
      responses:
        '201':
          description: Leitura criada com sucesso.
        '400':
          description: Dados inválidos.

    get:
      summary: Obter todas as leituras
      responses:
        '200':
          description: Lista de todas as leituras.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reading'
        '500':
          description: Erro no servidor.

  /readings/{id}:
    get:
      summary: Obter leitura por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da leitura.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
        '404':
          description: Leitura não encontrada.

    put:
      summary: Atualizar uma leitura
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reading'
      responses:
        '200':
          description: Leitura atualizada com sucesso.
        '400':
          description: Dados inválidos.

    delete:
      summary: Deletar uma leitura
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Leitura deletada com sucesso.
        '404':
          description: Leitura não encontrada.

  /users/register:
    post:
      summary: Registrar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Usuário registrado com sucesso.
        '400':
          description: Erro ao registrar usuário.

  /users/login:
    post:
      summary: Fazer login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login bem-sucedido.
        '401':
          description: Credenciais inválidas.

components:
  schemas:
    Reading:
      type: object
      properties:
        humidity:
          type: number
          example: 50
        temperature:
          type: number
          example: 22.5
        mq_sensor_value:
          type: number
          example: 450
        mq_voltage:
          type: number
          example: 2.5
        timestamp:
          type: string
          format: date-time
