openapi: 3.0.0
info:
  title: Sensor Data API
  version: 1.0.0
  description: API para gerenciar leituras de sensores, usuários e estatísticas.
servers:
  - url: http://localhost:5000
    description: Servidor local
  - url: https://airlytcs-backend.onrender.com
    description: Servidor de produção
paths:
  /readings:
    get:
      summary: Obter todas as leituras
      responses:
        '200':
          description: Lista de todas as leituras.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reading'
        '500':
          description: Erro no servidor.

  /readings/{id}:
    get:
      summary: Obter leitura por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da leitura.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
        '404':
          description: Leitura não encontrada.

  /users/register:
    post:
      summary: Registrar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Usuário registrado com sucesso.
        '400':
          description: Erro ao registrar usuário.

  /users/login:
    post:
      summary: Fazer login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login bem-sucedido.
        '401':
          description: Credenciais inválidas.

  /statistics/calculate:
    post:
      summary: Calcular estatísticas
      description: Calcula estatísticas com base nas leituras existentes e as armazena no banco de dados.
      responses:
        '200':
          description: Estatísticas calculadas e armazenadas com sucesso.
        '400':
          description: Nenhum dado encontrado para calcular estatísticas.
        '500':
          description: Erro ao calcular e salvar estatísticas.

  /statistics:
    get:
      summary: Obter estatísticas
      description: Retorna as estatísticas calculadas mais recentes.
      responses:
        '200':
          description: Estatísticas retornadas com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
        '404':
          description: Nenhuma estatística encontrada.
        '500':
          description: Erro ao buscar estatísticas.

components:
  schemas:
    Reading:
      type: object
      properties:
        humidity:
          type: number
          example: 50
        temperature:
          type: number
          example: 22.5
        mq_sensor_value:
          type: number
          example: 450
        mq_voltage:
          type: number
          example: 2.5
        timestamp:
          type: string
          format: date-time

    Statistics:
      type: object
      properties:
        humidity:
          $ref: '#/components/schemas/StatisticDetails'
        temperature:
          $ref: '#/components/schemas/StatisticDetails'
        createdAt:
          type: string
          format: date-time

    StatisticDetails:
      type: object
      properties:
        mean:
          type: number
        median:
          type: number
        mode:
          type: number
        standardDeviation:
          type: number
        skewness:
          type: number
        kurtosis:
          type: number
        futureProjection:
          type: object
          properties:
            slope:
              type: number
            intercept:
              type: number
            nextPrediction:
              type: number
        probability:
          type: number
        distribution:
          type: string
